version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # Mount app code for development hot-reloading
      # - ./app:/app/app
      # - ./static:/app/static
      - app_code:/app/app
      - db_data:/app/resume.db
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  db_data:
  app_code:
