name: Python CI

on:
  push:
    branches: [ "master" ] # Adjust branch names if needed
  pull_request:
    branches: [ "master" ] # Adjust branch names if needed

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"] # Specify Python versions to test against

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # Use the Makefile target for linting
        make lint

    - name: Test with pytest
      run: |
        # Use the Makefile target for testing
        make test
